import { useEffect } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";

/**
 * Deep Link Handler
 * 
 * This page handles QR code scans from external sources.
 * When someone scans a QR code generated by the app from outside,
 * it redirects them here with the connection code in the URL.
 * 
 * Flow:
 * - User scans QR code from external camera app
 * - Opens: https://networx-dusky.vercel.app/connect?code=ABC123
 * - This component checks if user is logged in
 * - If not logged in: redirect to /login with return URL
 * - If logged in: redirect to /qr-connect?code=ABC123
 */
export default function DeepLink() {
  const [searchParams] = useSearchParams();
  const { user } = useAuth();
  const navigate = useNavigate();

  const connectionCode = searchParams.get("code");

  useEffect(() => {
    if (!connectionCode) {
      // No code provided, redirect to home
      navigate("/");
      return;
    }

    if (!user) {
      // User not logged in, redirect to login
      // After login, they'll need to manually go to QR connect
      navigate(`/login`);
      return;
    }

    // User is logged in, redirect to QR connection with the code
    navigate(`/qr-connect?code=${connectionCode}`);
  }, [user, connectionCode, navigate]);

  return (
    <div className="min-h-screen flex items-center justify-center bg-networx-dark">
      <div className="text-center">
        <h1 className="text-4xl font-bold text-networx-light mb-4">
          Networx
        </h1>
        <p className="text-networx-light/60 mb-8">
          Processing your connection...
        </p>
        <div className="animate-pulse">
          <div className="h-12 w-12 bg-networx-primary rounded-full mx-auto"></div>
        </div>
      </div>
    </div>
  );
}
